### ISSUE TITLE
rasn dependency in core is not found

### ISSUE THREAD

**Issue by kaichaosun** [stamp-protocol/tracker#28]
It's using a relative path, do you forget to upload it to github? @orthecreedence

**Comment by orthecreedence** [comment]
You're right! I just updated `Cargo.toml` to point to a better location. Give it a pull and try again =]

**Comment by kaichaosun** [comment]
core is now success in build, but cli is still broken with missing dependencies in core, like 
```
error[E0432]: unresolved import `stamp_core::util::Lockable`
 --> src/util.rs:6:5
  |
6 |     util::Lockable,
  |     ^^^^^^^^^^^^^^ no `Lockable` in `util`

error[E0432]: unresolved import `stamp_core::identity::ClaimBin`
  --> src/commands/claim.rs:13:9
   |
13 |         ClaimBin,
   |         ^^^^^^^^ no `ClaimBin` in `identity`
```

**Comment by orthecreedence** [comment]
Sorry, try again. I had unpushed commits on cli.
